### ISSUE TITLE
Style based miscalcs/display error

### ISSUE THREAD

**Issue by Watevir** [j-cob44/max-hit-calc#21]
Max hit shown for Melee does not appear to take into account style bonuses correctly, always calculates as though player is on aggressive. This can be seen using full obsidian armour with splitsword zerker necklace and ring with rune boots/regen brace at 60str with a divine str potion. max hit calcs as 23 but it is only 23 with aggressive style and is instead 22 on defensive/accurate styles with above mentioned stats/gear

**Comment by j-cob44** [comment]
Hey @Watevir! 

Is this happening when you mouse over the item in your inventory, but correct once the item is equipped?

**Comment by j-cob44** [comment]
Could you send a picture of your equipment screen when the problem is happening? I'll look into this and see if I can fix it for next update!

**Comment by Kubia-Beta** [comment]
Can't tell if this is the same issue causing this. Real max hit is 14, estimated 13 (spec is off too, should be 21, says 19). Was on Pummel (Aggressive)(Crush)(Str). Tooltip says the next max is in: 3str levels, 6str bonus, 6% prayer boost. 
Plugging this gear into a calculator, the calculations would be if I was on Accurate, but I am not. Switching styles has no effect.
![wrong max hit](https://github.com/j-cob44/max-hit-calc/assets/113896543/3d231609-4965-4df4-955a-1aaffd69c2df)
<img width="85" alt="wrong max hit pt2" src="https://github.com/j-cob44/max-hit-calc/assets/113896543/cfc0476f-07ed-4cbe-9fc6-4673b280f155">
<img width="567" alt="wrong max hit pt3" src="https://github.com/j-cob44/max-hit-calc/assets/113896543/c4dcd4b7-3d7a-406b-a13d-b67402dce963">

I was able to replicate the issue on the same setup as the images, but with a rune scimitar instead of a dragon mace. It again did not update the values for the prayer/str bonus/str levels when changing styles. With a rune scim, the max hit does not change, but on chop (accurate) it correctly lists 4 levels to next max, and on slash (aggressive) it says the same despite it actually taking only 1 max.

From equipping different items, it seems that the inventory max is overvalued while equipped is undervalued. This is true for multiple styles. When I pull out my two Rune Crossbows and Bronze Bolts, the one I have equipped gets a max hit of 8 on the calculator while the one in my inventory has a max hit of 9 on the same report. Very interestingly, it says I will gain a max hit in 2 levels, 2 bonus or 4% bonus. I actually gain a max hit with 5 bonus or 5 ranging levels.

In both cases, there appears to be a +3 bonus _somewhere_. So, I tried stripping to just the dragon mace with my iron's stats. It then said I needed 6 more strength bonus/levels, which is very odd because I would need 3. With an entirely naked character, it then reports that the mace in inventory maxes a 14 (not a 12) which is 14 strength bonus off. I'm not really sure what's going on here, since that's a helluva jump. Only something like the attack style mult being wrongly applied multiple times should even come close.

**Comment by j-cob44** [comment]
Hi @Kubia-Beta, from the pictures you've provided, you are using a different plugin than this one I have made. I believe you are using an old plugin that is no longer updated. Please try mine out! https://runelite.net/plugin-hub/show/max-hit-calculator

How I know this is true is that my plugin does not show decimals,
![image](https://github.com/j-cob44/max-hit-calc/assets/23692043/5b0cae05-7e45-45ca-b698-f5121e88b39b)
and the setting page currently looks like this,
![image](https://github.com/j-cob44/max-hit-calc/assets/23692043/96351fb4-e758-4482-8473-8b849411a2cf)

**Comment by j-cob44** [comment]
I'm not sure if this is both of your cases. @Watevir, please let me know if your issue still persists and if so, please post some screenshots of the issue.

**Comment by j-cob44** [comment]
Hi @Watevir, 

I've been trying to replicate this issue and I still am unable to. Please ensure you are using my [plugin](https://runelite.net/plugin-hub/show/max-hit-calculator), here is a screenshot of it in the external plugin section of Runelite.

![image](https://github.com/j-cob44/max-hit-calc/assets/23692043/18a76d8a-ac03-48ea-827e-6deeec83fdfe)

I believe you are using the older, outdated plugin which has not been updated for a few years now.
