### ISSUE TITLE
Throwable ranged weapons shouldn't factor ammunition slot range strength into max hit

### ISSUE THREAD

**Issue by jrequizo** [j-cob44/max-hit-calc#9]
As the title explains, thrown weapons such as darts and throwing knives incorrectly display a max hit value that includes the ranged strength bonus from equipment in the ammunition slot.

A proposed fix could add a check in this method:
https://github.com/j-cob44/max-hit-calc/blob/4988431151a7be6751480c19efdfcecba8135663/src/main/java/com/maxhitcalc/MaxHit.java#L300

This could be implemented as such on line 312 or beyond:
```
Item weapon = EquipmentItems.getItemIdInGivenSetSlot(playerEquipment, EquipmentInventorySlot.WEAPON);
ItemComposition weaponComposition = client.getItemDefinition(weapon);

boolean isWeaponStackable = weaponComposition.isStackable();
boolean isRanging = weaponAttackStyle == AttackStyle.RANGING || weaponAttackStyle == AttackStyle.LONGRANGE

if (isWeaponStackable && isRanging) {
    skipAmmo = true;
}
```
---

Looking at the OSRS wiki, throwing axes, knives, and darts all use the same three combat styles. It can therefore be assume that any equipped weapon that is either one of these three combat styles and is stackable is a thrown weapon and thus should ignore the ranged strength bonus from the ammunition slot.

The above code was put together from some preliminary investigation into the Runelite source and your plugin's source and still needs to be tested but could be useful as a starting point on fixing this issue.

**Comment by j-cob44** [comment]
Awesome work, I'll look into this implementation fix when I get back to my computer early next week, currently traveling. 

Thank you!

**Comment by j-cob44** [comment]
I loved the idea for using stackable as the identifier for thrown weapons, however in testing it seems that every weapon was considered stackable. Not really sure why, I'm assuming if it can be noted then technically its considered stackable. So, for instance the magic short bow would no longer consider ammo because it was being returned as stackable. Once again, not 100% sure why.

Anyways, using the ending names (thrownaxe, dart, and knife) as an identifier will work for now. 

https://github.com/j-cob44/max-hit-calc/blob/6caf2437eac8679915a3f0ab89bc5529cb61c3e6/src/main/java/com/maxhitcalc/MaxHit.java#L314-L324

I will be running more tests to make sure everything is working fine, but this will be pushed in the next update.

**Comment by j-cob44** [comment]
This will be updated in release 1.1.5 when accepted by the plugin hub: https://github.com/runelite/plugin-hub/pull/4630
